# Generated by Django 4.2.3 on 2023-07-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=8, verbose_name='NÚMERO DE SÉRIE')),
                ('tipo', models.IntegerField(choices=[(1, 'PISTOLA'), (2, 'ARMA LONGA')], verbose_name='TIPO')),
                ('modelo', models.IntegerField(choices=[(1, 'PT 100'), (2, 'SMT'), (3, 'CT')], verbose_name='MODELO')),
            ],
            options={
                'verbose_name': 'Cadastro de Arma',
                'verbose_name_plural': 'Cadastro de Armas',
            },
        ),
    ]
