# Generated by Django 4.2.3 on 2023-07-12 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('belico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('sub_quantidade', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[(1, 'COM POLICIAL'), (2, 'ENTREGUE')], max_length=10)),
                ('belico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belico.belico', verbose_name='BÉLICO')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cadastropolicial', verbose_name='POLICIAL')),
            ],
        ),
    ]
